sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: ULz/oIaWYWQpuTqoOtyH/yfPO9LhKhvF0UKjFHvq/gGDIOfOmcUZFhYjFB9pfAdF9Y6MBe4R4Nx11ppoTB0wPhjfmYLyQM+B4ePBd13Y+oKj3cTBBGVZXDSPFzr3TG3EDHyMbUE1KoKcL+80+oQtxW5fvPgWb719hCCnq/5QUa/v03hTusJmrLKvfHRKp9zo6tyJzpcUnlLM2EXymQ3iV03fgiCBZkMpaLRSl36Q8ppZ9YJvSatnSjnwX4I7wbUISG+d+F5O3xgibVJLCT3pk2PXF7BdXUasHgjqXtVr9LNxWC2hKINs549Hxko7eJD+iHswTvZlpC/kjfPJGe6kqoz6HAF0fY7NUJOgo55fRb2p6QL1iUOO4D78du0jQFPWJIpAcUh9Lw/uUi8JPkuJgCwg3f3bv3/uRl+QJNMtGONYLe44Wx2YrD4bIgyfpTJh7ohhSzcoBqw87FpMYX7agoK8Hz4Q4EEpN3rdB4cV6rCcUJMoISeXmLNDKaqo7AtX1g9Sdhz2eaMeriggMjue/xaAqW6fYdjBIrT9yZE9obGZnutlMrCGiqDws4JXPMmpL7j8uVkr6hKUS4jTCcLXqS4WjdnsM7bHHF/QHPjCmfrt3jQKHfSiMRLETPPy3HU/+0f3Q12qduvmV8pSj5+JzJFkjQYoNeatK5WisnpWp+Y=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: rSpx/gt03jlJcWk+5Cpc1AYL3ZLKs8GbRra/qVcXXul64d2vm1UFkSKcYYNezMsetDiId7t0iB/nEMUk0gyyZ/f3QTovIzN8AhnPo/EWBUvve2lnJBu+EnrBG/gTO2pTH2dVHj8+m379RlYbYxY9TTSjqouoczLi22euVkfVkgb9EnvaFZltumVRcoHUhVrEl+TDsOScgiSnedNroYinfqUgJ+RNIDKWFC4x1nSN7YzSdacZuazgFqKuKyYGROIo9iGSUVxJdpz8mGuTc+evRqBKLd0zEX5ci2y1RJoIoXwR2/HkTOW//vrKchMHM+kHUEO/38U3nvrXmyN++90Azj8EikAZ4im9uStJEBbUEKAgZJ/s1nmCwivF1Fm67O6HkEm5HaDRgVt8Sbek9mKKzw4qImwjeJCu9xjNcO19vyto5dj5Cre4uJ51Rf4PbioWSdVNmsD+AkJaOu16LGEjSl4ZYBIt9FxFkiqSc5N5yd1ouODXY+EM8ioB0pydJh0XhUy+E/vef4MT+GRDYSWZ8G8yoZ61nqkDoNeBzwD5mK28X0330Apm2e7OU29/oclIfaXOaCf58OMJFb6r4/VMCnLXWv4NutzKs2oPAVNsbHfJfhAeUjfm87JUHIMVMIpjMbfBJfWeq4Xx5CmxApkD9Re42wgjB2Qzs2eZll3mQCQ=
